excluded_course_keywords:
  - ADVISORY
  - "National Honor Society"
  - HOSA
  - "[Archive]"
  - LIBRARY
  - "SOC331"

sender_email: jrolstad@gmail.com

recipients:
  - rolstmac000@edmonds15.org
  - bvrbas@gmail.com
